name: DesACoudre
version: 1.0
main: fr.greanor.desacoudre.Main
api-version: 1.21

commands:
  dac:
    description: Commande principale du mini-jeu Dé à Coudre
    usage: /dac [start|setspawn|listpools|stop]

  createpool:
    description: Crée une nouvelle piscine en sélectionnant deux coins
    usage: /createpool <nom>

  deletepool:
    description: Supprime une piscine existante
    usage: /deletePool <nom>